src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClientRepository::class)]
class Client
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $contact_details = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phone = null;

    #[ORM\ManyToOne(inversedBy: 'clients')]
    private ?Company $company = null;

    #[ORM\OneToMany(targetEntity: Invoice::class, mappedBy: 'client')]
    private Collection $invoices;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $website = null;

    #[ORM\ManyToOne(inversedBy: 'clients')]
    private ?User $user = null;

    public function __toString(): string
    {
        return (string) $this->name;
    }


    public function __construct()
    {
        $this->invoices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getContactDetails(): ?string
    {
        return $this->contact_details;
    }

    public function setContactDetails(?string $contact_details): static
    {
        $this->contact_details = $contact_details;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): static
    {
        $this->company = $company;

        return $this;
    }

    /**
     * @return Collection<int, Invoice>
     */
    public function getInvoices(): Collection
    {
        return $this->invoices;
    }

    public function addInvoice(Invoice $invoice): static
    {
        if (!$this->invoices->contains($invoice)) {
            $this->invoices->add($invoice);
            $invoice->setClient($this);
        }

        return $this;
    }

    public function removeInvoice(Invoice $invoice): static
    {
        if ($this->invoices->removeElement($invoice)) {
            // set the owning side to null (unless already changed)
            if ($invoice->getClient() === $this) {
                $invoice->setClient(null);
            }
        }

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): static
    {
        $this->website = $website;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/Company.php
<?php

namespace App\Entity;

use App\Repository\CompanyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CompanyRepository::class)]
class Company
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $companyName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logoPath = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phone = null;

    #[ORM\OneToMany(targetEntity: Client::class, mappedBy: 'company')]
    private Collection $clients;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $website = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo_type = null;

    #[ORM\ManyToOne(inversedBy: 'companies')]
    private ?User $user = null;

    public function __toString(): string
    {
        return (string) $this->companyName;
    }


    public function __construct()
    {
        $this->clients = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCompanyName(): ?string
    {
        return $this->companyName;
    }

    public function setCompanyName(?string $companyName): static
    {
        $this->companyName = $companyName;

        return $this;
    }

    public function getLogoPath(): ?string
    {
        return $this->logoPath;
    }

    public function setLogoPath(?string $logoPath): static
    {
        $this->logoPath = $logoPath;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @return Collection<int, Client>
     */
    public function getClients(): Collection
    {
        return $this->clients;
    }

    public function addClient(Client $client): static
    {
        if (!$this->clients->contains($client)) {
            $this->clients->add($client);
            $client->setCompany($this);
        }

        return $this;
    }

    public function removeClient(Client $client): static
    {
        if ($this->clients->removeElement($client)) {
            // set the owning side to null (unless already changed)
            if ($client->getCompany() === $this) {
                $client->setCompany(null);
            }
        }

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): static
    {
        $this->website = $website;

        return $this;
    }

    public function getLogoType(): ?string
    {
        return $this->logo_type;
    }

    public function setLogoType(?string $logo_type): static
    {
        $this->logo_type = $logo_type;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/Invoice.php
<?php

namespace App\Entity;

use App\Repository\InvoiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InvoiceRepository::class)]
class Invoice
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $invoiceNumber = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $date = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $dueDate = null;

    #[ORM\Column(nullable: true)]
    private ?float $totalAmount = null;
    
    #[ORM\ManyToOne(inversedBy: 'invoices')]
    private ?Client $client = null;

    #[ORM\OneToMany(targetEntity: InvoiceItem::class, mappedBy: 'invoice')]
    private Collection $invoiceItems;

    #[ORM\ManyToOne(inversedBy: 'invoice')]
    private ?Notes $notes = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $payment_info = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $terms_conditions = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $type = null;

    #[ORM\Column(nullable: true)]
    private ?float $tax = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $tax_type = null;

    #[ORM\ManyToOne(inversedBy: 'invoices')]
    private ?User $user = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pages = null;

    #[ORM\ManyToOne(inversedBy: 'invoices')]
    private ?Theme $theme = null;

    #[ORM\Column(nullable: true)]
    private ?float $discount = null;

    public function __construct()
    {
        $this->invoiceItems = new ArrayCollection();
    }

    public function __toString(): string
    {
        return (string) $this->getClient()->getName() . "-" . $this->invoiceNumber;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInvoiceNumber(): ?string
    {
        return $this->invoiceNumber;
    }

    public function setInvoiceNumber(?string $invoiceNumber): static
    {
        $this->invoiceNumber = $invoiceNumber;

        return $this;
    }

    public function getDate(): ?\DateTimeImmutable
    {
        return $this->date;
    }

    public function setDate(?\DateTimeImmutable $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getDueDate(): ?\DateTimeImmutable
    {
        return $this->dueDate;
    }

    public function setDueDate(?\DateTimeImmutable $dueDate): static
    {
        $this->dueDate = $dueDate;

        return $this;
    }

    public function getTotalAmount(): ?float
    {
        return $this->totalAmount;
    }

    public function setTotalAmount(?float $totalAmount): static
    {
        $this->totalAmount = $totalAmount;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): static
    {
        $this->client = $client;

        return $this;
    }

    /**
     * @return Collection<int, InvoiceItem>
     */
    public function getInvoiceItems(): Collection
    {
        return $this->invoiceItems;
    }

    public function addInvoiceItem(InvoiceItem $invoiceItem): static
    {
        if (!$this->invoiceItems->contains($invoiceItem)) {
            $this->invoiceItems->add($invoiceItem);
            $invoiceItem->setInvoice($this);
        }

        return $this;
    }

    public function removeInvoiceItem(InvoiceItem $invoiceItem): static
    {
        if ($this->invoiceItems->removeElement($invoiceItem)) {
            // set the owning side to null (unless already changed)
            if ($invoiceItem->getInvoice() === $this) {
                $invoiceItem->setInvoice(null);
            }
        }

        return $this;
    }

    public function getNotes(): ?Notes
    {
        return $this->notes;
    }

    public function setNotes(?Notes $notes): static
    {
        $this->notes = $notes;

        return $this;
    }

    public function getPaymentInfo(): ?string
    {
        return $this->payment_info;
    }

    public function setPaymentInfo(?string $payment_info): static
    {
        $this->payment_info = $payment_info;

        return $this;
    }

    public function getTermsConditions(): ?string
    {
        return $this->terms_conditions;
    }

    public function setTermsConditions(?string $terms_conditions): static
    {
        $this->terms_conditions = $terms_conditions;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getTax(): ?float
    {
        return $this->tax;
    }

    public function setTax(?float $tax): static
    {
        $this->tax = $tax;

        return $this;
    }

    public function getTaxType(): ?string
    {
        return $this->tax_type;
    }

    public function setTaxType(?string $tax_type): static
    {
        $this->tax_type = $tax_type;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getPages(): ?string
    {
        return $this->pages;
    }

    public function setPages(?string $pages): static
    {
        $this->pages = $pages;

        return $this;
    }

    public function getTheme(): ?Theme
    {
        return $this->theme;
    }

    public function setTheme(?Theme $theme): static
    {
        $this->theme = $theme;

        return $this;
    }

    public function getDiscount(): ?float
    {
        return $this->discount;
    }

    public function setDiscount(?float $discount): static
    {
        $this->discount = $discount;

        return $this;
    }
}

src/Entity/Theme.php
<?php

namespace App\Entity;

use App\Repository\ThemeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ThemeRepository::class)]
class Theme
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pri_color = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $sec_color = null;

    #[ORM\ManyToOne(inversedBy: 'themes')]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'themes')]
    private ?Template $template = null;

    #[ORM\OneToMany(targetEntity: Invoice::class, mappedBy: 'theme')]
    private Collection $invoices;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    public function __construct()
    {
        $this->invoices = new ArrayCollection();
    }

    public function __toString(): string
    {
        return (string) $this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPriColor(): ?string
    {
        return $this->pri_color;
    }

    public function setPriColor(?string $pri_color): static
    {
        $this->pri_color = $pri_color;

        return $this;
    }

    public function getSecColor(): ?string
    {
        return $this->sec_color;
    }

    public function setSecColor(?string $sec_color): static
    {
        $this->sec_color = $sec_color;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getTemplate(): ?Template
    {
        return $this->template;
    }

    public function setTemplate(?Template $template): static
    {
        $this->template = $template;

        return $this;
    }

    /**
     * @return Collection<int, Invoice>
     */
    public function getInvoices(): Collection
    {
        return $this->invoices;
    }

    public function addInvoice(Invoice $invoice): static
    {
        if (!$this->invoices->contains($invoice)) {
            $this->invoices->add($invoice);
            $invoice->setTheme($this);
        }

        return $this;
    }

    public function removeInvoice(Invoice $invoice): static
    {
        if ($this->invoices->removeElement($invoice)) {
            // set the owning side to null (unless already changed)
            if ($invoice->getTheme() === $this) {
                $invoice->setTheme(null);
            }
        }

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }
}

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Get Invoice{% endblock %}

{% block body %}
<h1>Get Invoice</h1>
<form method="get" action="{{path('invoice_generator')}}">
    <input type="text" name="i-n" placeholder="Invoice Number">
    <button type="submit">Get Invoice</button>
</form>
{% endblock %}

templates/index/it.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{invoice.client.name}} | {{invoice.type}} | {{invoice.invoiceNumber}} {% endblock %}
{% block stylesheets %}
<style>
.invoice_style3 .invoice-table thead th {
    background: -webkit-linear-gradient(top, {{invoice.theme.priColor}} -35.51%, #000000 196.64%);
    background: linear-gradient(180deg, {{invoice.theme.priColor}} -35.51%, #000000 196.64%);
}
{% if invoice.invoiceItems|length > 4 %}
@media print {
    body {
    zoom: 95%; /* Adjust the percentage as needed to fit content on one page */
  }
}
{% endif %}
</style>
{% endblock %}
{% block body %}
<body class="it-template">
{% set logo_width = invoice.client.company.logoType == 'square' ? 150 : 300 %}
{% set max_height = invoice.client.company.logoType == 'square' ? 150 : 70 %}

    <!--[if lte IE 9]>
    	<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->


    <!--********************************
   		Code Start From Here 
	******************************** -->

    <div class="invoice-container-wrap">
        <div class="invoice-container">
            <main>
                <!--==============================
Invoice Area
==============================-->
                <div class="th-invoice invoice_style3">
                    <div class="download-inner" id="download_section">
                        <!--==============================
	Header Area
==============================-->
                        <header class="th-header header-layout2">
                            <div class="row align-items-start justify-content-between">
                                <div class="col-auto">
                                    <div class="header-logo">
                                        <a href="{{invoice.client.company.website}}"><img style="max-width:{{logo_width}}px;max-height:{{max_height}}px" src="/invoices/images/{{invoice.client.company.logoPath}}" alt="Joe SEO Invoice Generator"></a>
                                    </div>
                                </div>
                                <div class="col-auto">
                                    <h1 class="big-title">{{invoice.type}}</h1>
                                </div>
                            </div>
                        </header>
                        <div class="row justify-content-between mb-30 mt-40 pt-3">
                            <div class="col-auto">
                                {% if invoice.type == 'invoice' %}
                                <div class="invoice-left">
                                    <b>Invoiced To:</b>
                                    <address>
                                        {{invoice.client.name}} <br>
                                        {{invoice.client.contactDetails}} <br>
                                        {{invoice.client.address}} <br>
                                        {{invoice.client.email}} <br>
                                        {{invoice.client.phone}} <br>
                                    </address>
                                </div>
                                {% endif %}
                            </div>
                            <div class="col-auto">
                                <b>From:</b>
                                <address>
                                    {{invoice.client.company.email}}<br>
                                    {{invoice.client.company.phone}}<br>
                                    {{invoice.client.company.website}}<br>
                                </address>

                                <p class="invoice-number mb-2 pb-1"><b>{{invoice.type|title}} No: </b>#{{invoice.invoiceNumber}}</p>
                                <p class="invoice-date"><b>Date: </b>{{invoice.date|date('d-m-Y')}}</p>
                                {% if invoice.type == 'invoice' %}<p class="invoice-date"><b>Due Date: </b>{{invoice.dueDate|date('d-m-Y')}}</p>{% endif %}
                            </div>
                        </div>
                        <table class="invoice-table td-big table-stripe-column">
                            <thead>
                                <tr>
                                    <th>SL</th>
                                    <th>Service Description</th>
                                    <th>Price</th>
                                    <th>Qty</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for item in invoice.invoiceItems %}
                                <tr>
                                    <td>{{loop.index}}</td>
                                    <td>{{item.description}}</td>
                                    <td>{{item.unitPrice|number_format}}</td>
                                    <td>{{item.quantity}}</td>
                                    <td>{{item.totalAmount|number_format}}</td>
                                </tr>
                            {% endfor %}
                            {% if invoice.invoiceItems|length < 3 %}                            
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                            {% endif %}
                            </tbody>
                        </table>
                        <div class="row justify-content-between">
                            <div class="col-auto">
                                {% if invoice.type == 'invoice' %}
                                <div class="invoice-left text-white mb-30">
                                    <b>Payment Info:</b>
                                    <p style="max-width:280px;" class="mb-0">{{invoice.paymentInfo|nl2br}}</p>
                                </div>
                                {% endif %}
                                <div class="invoice-left text-white">
                                    <b>Terms & Conditions</b>
                                    <p style="max-width:280px;" class="mb-0">{{invoice.termsConditions|nl2br}}</p>
                                </div>
                            </div>
                            <div class="col-auto">
                            {% if invoice.taxType == 'inclusive' %}
                                <table class="total-table">
                                    <tr>
                                        <th>Sub Total:</th>
                                        <td>KSh {{invoice.totalAmount|number_format}}</td>
                                    </tr>
                                    <tr>
                                        <th>Tax:</th>
                                        <td>KSh {{invoice.tax|number_format}}</td>
                                    </tr>
                                    <tr>
                                        <th>Discount:</th>
                                        <td>KSh {{invoice.discount|number_format}}</td>
                                    </tr>
                                    {% set finalAmount = (invoice.totalAmount - invoice.tax) - invoice.discount %}
                                    <tr>
                                        <th>Total:</th>
                                        <td>KSh {{finalAmount|number_format}}</td>
                                    </tr>
                                </table>
                            {% else %}
                                <table class="total-table">
                                    <tr>
                                        <th>Sub Total:</th>
                                        <td>KSh {{invoice.totalAmount|number_format}}</td>
                                    </tr>                                    
                                    <tr>
                                        <th>Tax:</th>
                                        <td>KSh {{invoice.tax|number_format}}</td>
                                    </tr>
                                    <tr>
                                        <th>Discount:</th>
                                        <td>KSh {{invoice.discount|number_format}}</td>
                                    </tr>
                                    {% set finalAmount = (invoice.totalAmount + invoice.tax) - invoice.discount %}
                                    <tr>
                                        <th>Total:</th>
                                        <td>KSh {{finalAmount|number_format}}</td>
                                    </tr>
                                </table>
                            {% endif %}
                                <div class="invoice-note2 mt-25">
                                    <p style="width:200px;" class="mb-0"><b>NOTE:</b> {{invoice.notes|nl2br}}.</p>
                                </div>
                            </div>
                        </div>
                        <div class="body-shape1">
                            <svg width="416" height="139" viewBox="0 0 416 139" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M366.015 139H0L61.7157 0H416L366.015 139Z" fill="url(#paint0_linear_307_104)" />
                                <defs>
                                    <linearGradient id="paint0_linear_307_104" x1="280.311" y1="-75.7221" x2="280.311" y2="120.434" gradientUnits="userSpaceOnUse">
                                        <stop offset="0.1344" stop-color="{{invoice.theme.secColor}}" />
                                        <stop offset="1" stop-color="{{invoice.theme.priColor}}" />
                                    </linearGradient>
                                </defs>
                            </svg>
                        </div>
                        <div class="body-shape2">
                            <svg width="498" height="405" viewBox="0 0 498 405" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M309.963 405H0V0H498L309.963 405Z" fill="url(#paint0_linear_307_1187)" />
                                <defs>
                                    <linearGradient id="paint0_linear_307_1187" x1="335.564" y1="-220.629" x2="335.564" y2="350.906" gradientUnits="userSpaceOnUse">
                                        <stop offset="0.1344" stop-color="{{invoice.theme.secColor}}" />
                                        <stop offset="1" stop-color="{{invoice.theme.priColor}}" />
                                    </linearGradient>
                                </defs>
                            </svg>
                        </div>
                    </div>
                    {% include ('tmp/buttons.html.twig') %}
                </div>


            </main>
        </div>
    </div>
    <!-- Invoice Conainter End -->
{% endblock %}